package vm

import (
	"reflect"
	"testing"

	"github.com/Benehiko/vee/internal/qemu"
)

func TestParseDefaultRoute(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		wantVia string
		wantDev string
	}{
		{
			name:    "dhcp lan route",
			input:   "default via 192.168.1.1 dev enp1s0 proto dhcp src 192.168.1.5 metric 100",
			wantVia: "192.168.1.1",
			wantDev: "enp1s0",
		},
		{
			name:    "nordlynx no gateway",
			input:   "default dev nordlynx table 205 scope link",
			wantVia: "",
			wantDev: "nordlynx",
		},
		{
			name:    "wireguard route",
			input:   "default dev wg0 scope link",
			wantVia: "",
			wantDev: "wg0",
		},
		{
			name:    "empty",
			input:   "",
			wantVia: "",
			wantDev: "",
		},
		{
			name:    "no default route",
			input:   "192.168.1.0/24 dev enp1s0 proto kernel scope link",
			wantVia: "",
			wantDev: "",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			via, dev := ParseDefaultRoute(tt.input)
			if via != tt.wantVia || dev != tt.wantDev {
				t.Errorf("ParseDefaultRoute() = (%q, %q), want (%q, %q)", via, dev, tt.wantVia, tt.wantDev)
			}
		})
	}
}

func TestParseDNSServers(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  []string
	}{
		{
			name:  "resolv.conf",
			input: "# Generated by NetworkManager\nnameserver 103.86.96.100\nnameserver 103.86.99.100\nsearch lan\n",
			want:  []string{"103.86.96.100", "103.86.99.100"},
		},
		{
			name:  "resolvectl",
			input: "Global: 1.1.1.1 8.8.8.8\nLink 2 (enp1s0): 192.168.1.1\n",
			want:  []string{"1.1.1.1", "8.8.8.8", "192.168.1.1"},
		},
		{
			name:  "resolvectl with iface suffix",
			input: "Link 2 (enp1s0): 192.168.1.1 fe80::1%enp1s0\n",
			want:  []string{"192.168.1.1", "fe80::1"},
		},
		{
			name:  "systemd stub resolv.conf",
			input: "nameserver 127.0.0.53\noptions edns0 trust-ad\n",
			want:  []string{"127.0.0.53"},
		},
		{
			name:  "dedup",
			input: "nameserver 1.1.1.1\nnameserver 1.1.1.1\n",
			want:  []string{"1.1.1.1"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ParseDNSServers(tt.input)
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("ParseDNSServers() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestParseUFWStatus(t *testing.T) {
	activeDeny := `Status: active
Logging: on (low)
Default: deny (incoming), deny (outgoing), disabled (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
22/tcp (OpenSSH)           ALLOW IN    Anywhere
8080/tcp                   ALLOW IN    Anywhere
Anywhere on wg0            ALLOW OUT   Anywhere
22/tcp                     ALLOW OUT   Anywhere
`
	got := ParseUFWStatus(activeDeny)
	if !got.Active {
		t.Error("expected Active")
	}
	if got.DefaultOutgoing != "deny" {
		t.Errorf("DefaultOutgoing = %q, want deny", got.DefaultOutgoing)
	}
	if got.RuleCount != 4 {
		t.Errorf("RuleCount = %d, want 4", got.RuleCount)
	}

	inactive := "Status: inactive\n"
	got = ParseUFWStatus(inactive)
	if got.Active {
		t.Error("expected inactive")
	}

	allowOut := "Status: active\nDefault: deny (incoming), allow (outgoing), disabled (routed)\n"
	got = ParseUFWStatus(allowOut)
	if got.DefaultOutgoing != "allow" {
		t.Errorf("DefaultOutgoing = %q, want allow", got.DefaultOutgoing)
	}
}

func TestParseNordVPNStatus(t *testing.T) {
	connected := "\r-\r\\\rStatus: Connected\nHostname: de1234.nordvpn.com\nIP: 185.130.184.90\nCountry: Germany\nCity: Frankfurt\nCurrent technology: NORDLYNX\nTransfer: 1.2 MiB received, 0.5 MiB sent\n"
	ok, server, detail := ParseNordVPNStatus(connected)
	if !ok {
		t.Error("expected connected")
	}
	if server != "de1234.nordvpn.com" {
		t.Errorf("server = %q", server)
	}
	if detail == "" {
		t.Error("expected non-empty detail")
	}

	disconnected := "Status: Disconnected\n"
	ok, _, _ = ParseNordVPNStatus(disconnected)
	if ok {
		t.Error("expected disconnected")
	}

	daemonDead := "We couldn't reach System Daemon.\n"
	ok, _, detail = ParseNordVPNStatus(daemonDead)
	if ok {
		t.Error("expected disconnected when daemon is unreachable")
	}
	if detail != "We couldn't reach System Daemon." {
		t.Errorf("detail = %q, want the raw daemon error", detail)
	}
}

func TestParseNordVPNSettings(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{"enabled", "Technology: NORDLYNX\nFirewall: enabled\nKill Switch: enabled\nAuto-connect: enabled\n", "on"},
		{"disabled", "Kill Switch: disabled\n", "off"},
		{"missing", "Technology: NORDLYNX\n", ""},
		{"spinner prefix", "\r-\rKill Switch: enabled\n", "on"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := ParseNordVPNSettings(tt.input); got != tt.want {
				t.Errorf("ParseNordVPNSettings() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestParseWGShow(t *testing.T) {
	up := `interface: wg0
  public key: abc123=
  private key: (hidden)
  listening port: 51820

peer: def456=
  endpoint: 185.65.135.1:51820
  allowed ips: 0.0.0.0/0
  latest handshake: 1 minute, 5 seconds ago
  transfer: 12.5 MiB received, 1.2 MiB sent
`
	endpoint, handshake := ParseWGShow(up)
	if endpoint != "185.65.135.1:51820" {
		t.Errorf("endpoint = %q", endpoint)
	}
	if handshake != "handshake 1 minute, 5 seconds ago" {
		t.Errorf("handshake = %q", handshake)
	}

	never := "interface: wg0\n  public key: abc123=\n\npeer: def456=\n  endpoint: 185.65.135.1:51820\n  allowed ips: 0.0.0.0/0\n"
	_, handshake = ParseWGShow(never)
	if handshake != "" {
		t.Errorf("handshake = %q, want empty (never completed)", handshake)
	}
}

func TestParseCloudflareTrace(t *testing.T) {
	trace := "fl=123f45\nh=www.cloudflare.com\nip=185.130.184.90\nts=1754700000.123\nvisit_scheme=https\n"
	if got := ParseCloudflareTrace(trace); got != "185.130.184.90" {
		t.Errorf("ParseCloudflareTrace() = %q", got)
	}
	if got := ParseCloudflareTrace("no ip line here"); got != "" {
		t.Errorf("ParseCloudflareTrace() = %q, want empty", got)
	}
}

func TestParseIPAddrBrief(t *testing.T) {
	input := `1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: enp1s0    inet 192.168.1.5/24 brd 192.168.1.255 scope global dynamic enp1s0\       valid_lft 85822sec preferred_lft 85822sec
2: enp1s0    inet6 fe80::5054:ff:fe12:3456/64 scope link \       valid_lft forever preferred_lft forever
3: wg0    inet 10.5.0.2/32 scope global wg0\       valid_lft forever preferred_lft forever
`
	ifaces := ParseIPAddrBrief(input)
	if len(ifaces) != 3 {
		t.Fatalf("got %d interfaces, want 3", len(ifaces))
	}
	if ifaces[1].Name != "enp1s0" || len(ifaces[1].IPAddresses) != 2 {
		t.Errorf("enp1s0 parsed wrong: %+v", ifaces[1])
	}
	if ifaces[1].IPAddresses[0].IPAddress != "192.168.1.5" || ifaces[1].IPAddresses[0].Prefix != 24 {
		t.Errorf("enp1s0 addr parsed wrong: %+v", ifaces[1].IPAddresses[0])
	}
	if ifaces[2].Name != "wg0" || ifaces[2].IPAddresses[0].IPAddress != "10.5.0.2" {
		t.Errorf("wg0 parsed wrong: %+v", ifaces[2])
	}
}

func TestLanNetworks(t *testing.T) {
	ifaces := []qemu.GuestNetworkInterface{
		{Name: "lo", IPAddresses: []qemu.GuestIPAddress{{IPAddress: "127.0.0.1", Prefix: 8, IPAddressType: "ipv4"}}},
		{Name: "enp1s0", IPAddresses: []qemu.GuestIPAddress{{IPAddress: "192.168.1.5", Prefix: 24, IPAddressType: "ipv4"}}},
		{Name: "nordlynx", IPAddresses: []qemu.GuestIPAddress{{IPAddress: "10.5.0.2", Prefix: 32, IPAddressType: "ipv4"}}},
	}
	nets := lanNetworks(ifaces)
	if len(nets) != 1 {
		t.Fatalf("got %d networks, want 1 (lo and tunnel excluded)", len(nets))
	}
	if nets[0].String() != "192.168.1.0/24" {
		t.Errorf("network = %s, want 192.168.1.0/24", nets[0])
	}
}

func TestGuestChecksDNSLeak(t *testing.T) {
	cfg := &VMConfig{VPNProvider: "generic"}
	host := &HostNetwork{PublicIP: "82.1.2.3"}
	guest := &GuestNetwork{
		Interfaces: []qemu.GuestNetworkInterface{
			{Name: "enp1s0", IPAddresses: []qemu.GuestIPAddress{{IPAddress: "192.168.1.5", Prefix: 24, IPAddressType: "ipv4"}}},
			{Name: "wg0", IPAddresses: []qemu.GuestIPAddress{{IPAddress: "10.5.0.2", Prefix: 32, IPAddressType: "ipv4"}}},
		},
		DefaultRoute: "dev wg0",
		DNSServers:   []string{"192.168.1.1"},
		UFW:          UFWState{Available: true, Active: true, DefaultOutgoing: "deny", RuleCount: 5},
		VPN:          VPNState{Provider: "generic", Available: true, Connected: true, Endpoint: "185.65.135.1:51820"},
		EgressIP:     "185.65.135.1",
		DNSEgressIP:  "185.65.135.1",
	}
	checks := guestChecks(cfg, NetworkOptions{}, host, guest)
	got := map[string]string{}
	for _, c := range checks {
		got[c.Name] = c.Status
	}
	if got["guest:dns-leak"] != NetCheckFail {
		t.Errorf("dns-leak = %q, want fail (LAN resolver)", got["guest:dns-leak"])
	}
	for _, name := range []string{"guest:route", "guest:ufw", "guest:killswitch", "guest:vpn", "guest:egress-ip", "guest:dns-egress"} {
		if got[name] != NetCheckPass {
			t.Errorf("%s = %q, want pass", name, got[name])
		}
	}

	// VPN-egress DNS passes; egress matching the host fails.
	guest.DNSServers = []string{"103.86.96.100"}
	guest.EgressIP = "82.1.2.3"
	checks = guestChecks(cfg, NetworkOptions{}, host, guest)
	got = map[string]string{}
	for _, c := range checks {
		got[c.Name] = c.Status
	}
	if got["guest:dns-leak"] != NetCheckPass {
		t.Errorf("dns-leak = %q, want pass", got["guest:dns-leak"])
	}
	if got["guest:egress-ip"] != NetCheckFail {
		t.Errorf("egress-ip = %q, want fail (matches host)", got["guest:egress-ip"])
	}
}

func TestGuestChecksNonVPN(t *testing.T) {
	cfg := &VMConfig{}
	checks := guestChecks(cfg, NetworkOptions{}, &HostNetwork{}, &GuestNetwork{})
	if len(checks) != 0 {
		t.Errorf("non-VPN VM should have no guest judgments, got %v", checks)
	}
}
